name: Build Linux
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true


      - name: GCC
        run: |
          sudo apt update
          sudo apt install gcc-x86-64-linux-gnu gcc-i686-linux-gnu gcc-arm-linux-gnueabihf gcc-powerpc64le-linux-gnu gcc-riscv64-linux-gnu gcc-aarch64-linux-gnu

      - name: Build
        run: |
          ./build-zlib-linux.sh
          ./build-openssl-linux.sh
          ./build-libssh2-linux.sh

      - name: Upload zlib artifact
        uses: actions/upload-artifact@v4
        with:
          name: zlib-linux
          path: |
            zlib-linux-build/*/lib/*.a

      - name: Upload openssl artifact
        uses: actions/upload-artifact@v4
        with:
          name: openssl-linux
          path: |
            openssl-linux-build/*/lib*/*.a

      - name: Upload libssh2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: libssh2-linux
          path: |
            libssh2-linux-build/*/lib/*.a
            libssh2-linux-build/*/lib/*.so